### ISSUE TITLE
Getting the hex codes

### ISSUE THREAD

**Issue by JoFrhwld** [A-S500/dataviz_final-conleykinkead#1]
This would be a lot more work, so I’m not telling you to definitely do this, but there are packages out there to extract hex codes from image. So if you grabbed the official marketing image for each nail polish (probably better cause of controlled lighting in the image) you could get close to the exact color code with, e.g. colorfindr https://github.com/zumbov2/colorfindr

https://github.com/A-S500/dataviz_final-conleykinkead/blob/7801e59682c2e1e099d605ae5210fb664ae67782/visualization_final_report.qmd#L44

**Comment by conleykinkead** [comment]
cool! what a great idea! i tried colorfindr but it ended up being easier to grab the colors by hand.
